// <auto-generated />
namespace Guardias.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class Area_Guardia_updated_Semana_SemanaArea_SemanaGuardia_added : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Area_Guardia_updated_Semana_SemanaArea_SemanaGuardia_added));
        
        string IMigrationMetadata.Id
        {
            get { return "201412040207522_Area_Guardia_updated_Semana_SemanaArea_SemanaGuardia_added"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
