namespace Guardias.Migrations
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Migrations;
    using System.Linq;

    internal sealed class Configuration : DbMigrationsConfiguration<Guardias.Context>
    {
        public Configuration()
        {
            AutomaticMigrationsEnabled = false;
            ContextKey = "Guardias.Context";
        }

        protected override void Seed(Guardias.Context context)
        {
            //  This method will be called after migrating to the latest version.

            context.Unidades.AddOrUpdate(new Unidad[]
            {
                new Unidad { Id = 01, Numero = 97 },
                new Unidad { Id = 02, Numero = 96 },
                new Unidad { Id = 03, Numero = 95 },
                new Unidad { Id = 04, Numero = 94 },
                new Unidad { Id = 05, Numero = 93 },
                new Unidad { Id = 06, Numero = 92 },
                new Unidad { Id = 07, Numero = 91 },
                new Unidad { Id = 08, Numero = 90 },
                new Unidad { Id = 09, Numero = 89 },
                new Unidad { Id = 10, Numero = 88 },
                new Unidad { Id = 11, Numero = 87 },
                new Unidad { Id = 12, Numero = 86 },
                new Unidad { Id = 13, Numero = 85 },
                new Unidad { Id = 14, Numero = 84 },
                new Unidad { Id = 15, Numero = 83 },
                new Unidad { Id = 16, Numero = 82 },
                new Unidad { Id = 17, Numero = 81 },
                new Unidad { Id = 18, Numero = 80 },
                new Unidad { Id = 19, Numero = 79 },
                new Unidad { Id = 20, Numero = 78 },
                new Unidad { Id = 21, Numero = 77 },
                new Unidad { Id = 23, Numero = 76 },
                new Unidad { Id = 22, Numero = 75 },
                new Unidad { Id = 24, Numero = 74 },
                new Unidad { Id = 25, Numero = 73 },
                new Unidad { Id = 26, Numero = 72 },
                new Unidad { Id = 27, Numero = 71 },
                new Unidad { Id = 28, Numero = 70 },
                new Unidad { Id = 29, Numero = 69 },
                new Unidad { Id = 30, Numero = 68 },
                new Unidad { Id = 31, Numero = 67 },
                new Unidad { Id = 32, Numero = 66 },
                new Unidad { Id = 33, Numero = 65 },
                new Unidad { Id = 34, Numero = 64 },
                new Unidad { Id = 35, Numero = 63 },
                new Unidad { Id = 36, Numero = 62 },
                new Unidad { Id = 37, Numero = 61 },
                new Unidad { Id = 38, Numero = 60 },
                new Unidad { Id = 39, Numero = 59 },
                new Unidad { Id = 40, Numero = 58 },
                new Unidad { Id = 41, Numero = 57 },
                new Unidad { Id = 42, Numero = 56 },
                new Unidad { Id = 43, Numero = 55 },
                new Unidad { Id = 44, Numero = 54 },
                new Unidad { Id = 45, Numero = 53 },
                new Unidad { Id = 46, Numero = 52 },
                new Unidad { Id = 47, Numero = 51 },
                new Unidad { Id = 48, Numero = 50 },
                new Unidad { Id = 49, Numero = 49 },
                new Unidad { Id = 50, Numero = 48 },
                new Unidad { Id = 51, Numero = 47 },
                new Unidad { Id = 52, Numero = 46 },
                new Unidad { Id = 53, Numero = 45 },
                new Unidad { Id = 54, Numero = 44 },
                new Unidad { Id = 55, Numero = 43 },
                new Unidad { Id = 56, Numero = 42 },
                new Unidad { Id = 57, Numero = 41 },
                new Unidad { Id = 58, Numero = 40 },
                new Unidad { Id = 59, Numero = 39 },
                new Unidad { Id = 60, Numero = 38 },
                new Unidad { Id = 61, Numero = 37 },
                new Unidad { Id = 62, Numero = 36 },
                new Unidad { Id = 63, Numero = 35 },
                new Unidad { Id = 64, Numero = 34 },
                new Unidad { Id = 65, Numero = 33 },
                new Unidad { Id = 66, Numero = 32 },
                new Unidad { Id = 67, Numero = 31 },
                new Unidad { Id = 68, Numero = 30 },
                new Unidad { Id = 69, Numero = 29 },
                new Unidad { Id = 70, Numero = 28 },
                new Unidad { Id = 71, Numero = 27 },
                new Unidad { Id = 72, Numero = 26 },
                new Unidad { Id = 73, Numero = 25 },
                new Unidad { Id = 74, Numero = 24 },
                new Unidad { Id = 75, Numero = 23 },
                new Unidad { Id = 76, Numero = 22 },
                new Unidad { Id = 77, Numero = 21 },
                new Unidad { Id = 78, Numero = 20 },
                new Unidad { Id = 79, Numero = 19 },
                new Unidad { Id = 80, Numero = 18 },
                new Unidad { Id = 81, Numero = 17 },
                new Unidad { Id = 82, Numero = 16 },
                new Unidad { Id = 83, Numero = 15 },
                new Unidad { Id = 84, Numero = 14 },
                new Unidad { Id = 85, Numero = 13 },
                new Unidad { Id = 86, Numero = 12 },
                new Unidad { Id = 87, Numero = 11 },
                new Unidad { Id = 88, Numero = 10 },
                new Unidad { Id = 89, Numero = 09 },
                new Unidad { Id = 90, Numero = 08 },
                new Unidad { Id = 91, Numero = 07 },
                new Unidad { Id = 92, Numero = 06 },
                new Unidad { Id = 93, Numero = 05 },
                new Unidad { Id = 94, Numero = 04 },
                new Unidad { Id = 95, Numero = 03 },
                new Unidad { Id = 96, Numero = 02 },
                new Unidad { Id = 97, Numero = 01 },
            });

            context.Areas.AddOrUpdate(new Area[] 
            { 
                new Area { Id = 01, Nombre = "Casa Dorada" },
                new Area { Id = 02, Nombre = "Fiestamericana" },
                new Area { Id = 03, Nombre = "Finisterra" },
                new Area { Id = 04, Nombre = "Sheraton Hacienda del Mar" },
                new Area { Id = 05, Nombre = "Sheraton Hacienda del Mar / Fiestamericana" },
                new Area { Id = 06, Nombre = "Marina" },
                new Area { Id = 07, Nombre = "ME Cabo" },
                new Area { Id = 08, Nombre = "Meliá Cabo Real" },
                new Area { Id = 09, Nombre = "Pueblo Bonito" },
                new Area { Id = 10, Nombre = "Pueblo Bonito Pacifica" },
                new Area { Id = 11, Nombre = "Pueblo Bonito Sunset Beach" },
                new Area { Id = 12, Nombre = "Pueblo Bonito Sunset Beach / The Office" },
                new Area { Id = 13, Nombre = "Recorrido" },
                new Area { Id = 14, Nombre = "RIU" },
                new Area { Id = 15, Nombre = "Sheraton" },
                new Area { Id = 16, Nombre = "Sitio° (plaza Amelia Wilkes)" },
                new Area { Id = 17, Nombre = "Sitio" },
                new Area { Id = 18, Nombre = "Sitio / Finisterra" },
                new Area { Id = 19, Nombre = "Sitio / Pueblo Bonito Sunset Beach" },
                new Area { Id = 20, Nombre = "Sitio / Walmart" },
                new Area { Id = 21, Nombre = "The Giggling Marlin" },
                new Area { Id = 22, Nombre = "The Office" },
                new Area { Id = 23, Nombre = "Walmart" },
                new Area { Id = 24, Nombre = "Walmart / ME Cabo" },
                new Area { Id = 25, Nombre = "Wyndham" }
            });

            context.Semanas.AddOrUpdate(new Semana[]
            {
                new Semana { Id = 01, Numero = 01 },
                new Semana { Id = 02, Numero = 02 },
                new Semana { Id = 03, Numero = 03 },
                new Semana { Id = 04, Numero = 04 },
                new Semana { Id = 05, Numero = 05 },
                new Semana { Id = 06, Numero = 06 }
            });

            context.SemanasAreas.AddOrUpdate(new SemanaArea[] 
            {
                // Semana #1
                new SemanaArea { Id = 001, Posicion = 01, SemanaId = 01, AreaId = 00 },
                new SemanaArea { Id = 002, Posicion = 02, SemanaId = 01, AreaId = 00 },
                new SemanaArea { Id = 003, Posicion = 03, SemanaId = 01, AreaId = 00 },
                new SemanaArea { Id = 004, Posicion = 04, SemanaId = 01, AreaId = 00 },
                new SemanaArea { Id = 005, Posicion = 05, SemanaId = 01, AreaId = 00 },
                new SemanaArea { Id = 006, Posicion = 06, SemanaId = 01, AreaId = 00 },
                new SemanaArea { Id = 007, Posicion = 07, SemanaId = 01, AreaId = 00 },
                new SemanaArea { Id = 008, Posicion = 08, SemanaId = 01, AreaId = 00 },
                new SemanaArea { Id = 009, Posicion = 09, SemanaId = 01, AreaId = 00 },
                new SemanaArea { Id = 010, Posicion = 10, SemanaId = 01, AreaId = 00 },
                new SemanaArea { Id = 011, Posicion = 11, SemanaId = 01, AreaId = 00 },
                new SemanaArea { Id = 012, Posicion = 12, SemanaId = 01, AreaId = 00 },
                new SemanaArea { Id = 013, Posicion = 13, SemanaId = 01, AreaId = 00 },
                new SemanaArea { Id = 014, Posicion = 14, SemanaId = 01, AreaId = 00 },
                new SemanaArea { Id = 015, Posicion = 15, SemanaId = 01, AreaId = 00 },
                new SemanaArea { Id = 016, Posicion = 16, SemanaId = 01, AreaId = 00 },
                new SemanaArea { Id = 017, Posicion = 17, SemanaId = 01, AreaId = 00 },
                new SemanaArea { Id = 018, Posicion = 18, SemanaId = 01, AreaId = 00 },
                new SemanaArea { Id = 019, Posicion = 19, SemanaId = 01, AreaId = 00 },
                new SemanaArea { Id = 020, Posicion = 20, SemanaId = 01, AreaId = 00 },

                // Semana #2
                new SemanaArea { Id = 021, Posicion = 01, SemanaId = 02, AreaId = 00 },
                new SemanaArea { Id = 022, Posicion = 02, SemanaId = 02, AreaId = 00 },
                new SemanaArea { Id = 023, Posicion = 03, SemanaId = 02, AreaId = 00 },
                new SemanaArea { Id = 024, Posicion = 04, SemanaId = 02, AreaId = 00 },
                new SemanaArea { Id = 025, Posicion = 05, SemanaId = 02, AreaId = 00 },
                new SemanaArea { Id = 026, Posicion = 06, SemanaId = 02, AreaId = 00 },
                new SemanaArea { Id = 027, Posicion = 07, SemanaId = 02, AreaId = 00 },
                new SemanaArea { Id = 028, Posicion = 08, SemanaId = 02, AreaId = 00 },
                new SemanaArea { Id = 029, Posicion = 09, SemanaId = 02, AreaId = 00 },
                new SemanaArea { Id = 030, Posicion = 10, SemanaId = 02, AreaId = 00 },
                new SemanaArea { Id = 031, Posicion = 11, SemanaId = 02, AreaId = 00 },
                new SemanaArea { Id = 032, Posicion = 12, SemanaId = 02, AreaId = 00 },
                new SemanaArea { Id = 033, Posicion = 13, SemanaId = 02, AreaId = 00 },
                new SemanaArea { Id = 034, Posicion = 14, SemanaId = 02, AreaId = 00 },
                new SemanaArea { Id = 035, Posicion = 15, SemanaId = 02, AreaId = 00 },
                new SemanaArea { Id = 036, Posicion = 16, SemanaId = 02, AreaId = 00 },
                new SemanaArea { Id = 037, Posicion = 17, SemanaId = 02, AreaId = 00 },
                new SemanaArea { Id = 038, Posicion = 18, SemanaId = 02, AreaId = 00 },
                new SemanaArea { Id = 039, Posicion = 19, SemanaId = 02, AreaId = 00 },
                new SemanaArea { Id = 030, Posicion = 20, SemanaId = 02, AreaId = 00 },

                // Semana #3
                new SemanaArea { Id = 031, Posicion = 01, SemanaId = 03, AreaId = 00 },
                new SemanaArea { Id = 032, Posicion = 02, SemanaId = 03, AreaId = 00 },
                new SemanaArea { Id = 033, Posicion = 03, SemanaId = 03, AreaId = 00 },
                new SemanaArea { Id = 034, Posicion = 04, SemanaId = 03, AreaId = 00 },
                new SemanaArea { Id = 035, Posicion = 05, SemanaId = 03, AreaId = 00 },
                new SemanaArea { Id = 036, Posicion = 06, SemanaId = 03, AreaId = 00 },
                new SemanaArea { Id = 037, Posicion = 07, SemanaId = 03, AreaId = 00 },
                new SemanaArea { Id = 038, Posicion = 08, SemanaId = 03, AreaId = 00 },
                new SemanaArea { Id = 039, Posicion = 09, SemanaId = 03, AreaId = 00 },
                new SemanaArea { Id = 040, Posicion = 10, SemanaId = 03, AreaId = 00 },
                new SemanaArea { Id = 041, Posicion = 11, SemanaId = 03, AreaId = 00 },
                new SemanaArea { Id = 042, Posicion = 12, SemanaId = 03, AreaId = 00 },
                new SemanaArea { Id = 043, Posicion = 13, SemanaId = 03, AreaId = 00 },
                new SemanaArea { Id = 044, Posicion = 14, SemanaId = 03, AreaId = 00 },
                new SemanaArea { Id = 045, Posicion = 15, SemanaId = 03, AreaId = 00 },
                new SemanaArea { Id = 046, Posicion = 16, SemanaId = 03, AreaId = 00 },
                new SemanaArea { Id = 047, Posicion = 17, SemanaId = 03, AreaId = 00 },
                new SemanaArea { Id = 048, Posicion = 18, SemanaId = 03, AreaId = 00 },
                new SemanaArea { Id = 049, Posicion = 19, SemanaId = 03, AreaId = 00 },
                new SemanaArea { Id = 040, Posicion = 20, SemanaId = 03, AreaId = 00 },

                // Semana #4
                new SemanaArea { Id = 041, Posicion = 01, SemanaId = 04, AreaId = 00 },
                new SemanaArea { Id = 042, Posicion = 02, SemanaId = 04, AreaId = 00 },
                new SemanaArea { Id = 043, Posicion = 03, SemanaId = 04, AreaId = 00 },
                new SemanaArea { Id = 044, Posicion = 04, SemanaId = 04, AreaId = 00 },
                new SemanaArea { Id = 045, Posicion = 05, SemanaId = 04, AreaId = 00 },
                new SemanaArea { Id = 046, Posicion = 06, SemanaId = 04, AreaId = 00 },
                new SemanaArea { Id = 047, Posicion = 07, SemanaId = 04, AreaId = 00 },
                new SemanaArea { Id = 048, Posicion = 08, SemanaId = 04, AreaId = 00 },
                new SemanaArea { Id = 049, Posicion = 09, SemanaId = 04, AreaId = 00 },
                new SemanaArea { Id = 050, Posicion = 10, SemanaId = 04, AreaId = 00 },
                new SemanaArea { Id = 051, Posicion = 11, SemanaId = 04, AreaId = 00 },
                new SemanaArea { Id = 052, Posicion = 12, SemanaId = 04, AreaId = 00 },
                new SemanaArea { Id = 053, Posicion = 13, SemanaId = 04, AreaId = 00 },
                new SemanaArea { Id = 054, Posicion = 14, SemanaId = 04, AreaId = 00 },
                new SemanaArea { Id = 055, Posicion = 15, SemanaId = 04, AreaId = 00 },
                new SemanaArea { Id = 056, Posicion = 16, SemanaId = 04, AreaId = 00 },
                new SemanaArea { Id = 057, Posicion = 17, SemanaId = 04, AreaId = 00 },
                new SemanaArea { Id = 058, Posicion = 18, SemanaId = 04, AreaId = 00 },
                new SemanaArea { Id = 059, Posicion = 19, SemanaId = 04, AreaId = 00 },
                new SemanaArea { Id = 060, Posicion = 20, SemanaId = 04, AreaId = 00 },

                // Semana #5
                new SemanaArea { Id = 061, Posicion = 01, SemanaId = 05, AreaId = 00 },
                new SemanaArea { Id = 062, Posicion = 02, SemanaId = 05, AreaId = 00 },
                new SemanaArea { Id = 063, Posicion = 03, SemanaId = 05, AreaId = 00 },
                new SemanaArea { Id = 064, Posicion = 04, SemanaId = 05, AreaId = 00 },
                new SemanaArea { Id = 065, Posicion = 05, SemanaId = 05, AreaId = 00 },
                new SemanaArea { Id = 066, Posicion = 06, SemanaId = 05, AreaId = 00 },
                new SemanaArea { Id = 067, Posicion = 07, SemanaId = 05, AreaId = 00 },
                new SemanaArea { Id = 068, Posicion = 08, SemanaId = 05, AreaId = 00 },
                new SemanaArea { Id = 069, Posicion = 09, SemanaId = 05, AreaId = 00 },
                new SemanaArea { Id = 070, Posicion = 10, SemanaId = 05, AreaId = 00 },
                new SemanaArea { Id = 071, Posicion = 11, SemanaId = 05, AreaId = 00 },
                new SemanaArea { Id = 072, Posicion = 12, SemanaId = 05, AreaId = 00 },
                new SemanaArea { Id = 073, Posicion = 13, SemanaId = 05, AreaId = 00 },
                new SemanaArea { Id = 074, Posicion = 14, SemanaId = 05, AreaId = 00 },
                new SemanaArea { Id = 075, Posicion = 15, SemanaId = 05, AreaId = 00 },
                new SemanaArea { Id = 076, Posicion = 16, SemanaId = 05, AreaId = 00 },
                new SemanaArea { Id = 077, Posicion = 17, SemanaId = 05, AreaId = 00 },
                new SemanaArea { Id = 078, Posicion = 18, SemanaId = 05, AreaId = 00 },
                new SemanaArea { Id = 079, Posicion = 19, SemanaId = 05, AreaId = 00 },
                new SemanaArea { Id = 080, Posicion = 20, SemanaId = 05, AreaId = 00 },

                // Semana #6
                new SemanaArea { Id = 081, Posicion = 01, SemanaId = 06, AreaId = 00 },
                new SemanaArea { Id = 082, Posicion = 02, SemanaId = 06, AreaId = 00 },
                new SemanaArea { Id = 083, Posicion = 03, SemanaId = 06, AreaId = 00 },
                new SemanaArea { Id = 084, Posicion = 04, SemanaId = 06, AreaId = 00 },
                new SemanaArea { Id = 085, Posicion = 05, SemanaId = 06, AreaId = 00 },
                new SemanaArea { Id = 086, Posicion = 06, SemanaId = 06, AreaId = 00 },
                new SemanaArea { Id = 087, Posicion = 07, SemanaId = 06, AreaId = 00 },
                new SemanaArea { Id = 088, Posicion = 08, SemanaId = 06, AreaId = 00 },
                new SemanaArea { Id = 089, Posicion = 09, SemanaId = 06, AreaId = 00 },
                new SemanaArea { Id = 090, Posicion = 10, SemanaId = 06, AreaId = 00 },
                new SemanaArea { Id = 091, Posicion = 11, SemanaId = 06, AreaId = 00 },
                new SemanaArea { Id = 092, Posicion = 12, SemanaId = 06, AreaId = 00 },
                new SemanaArea { Id = 093, Posicion = 13, SemanaId = 06, AreaId = 00 },
                new SemanaArea { Id = 094, Posicion = 14, SemanaId = 06, AreaId = 00 },
                new SemanaArea { Id = 095, Posicion = 15, SemanaId = 06, AreaId = 00 },
                new SemanaArea { Id = 096, Posicion = 16, SemanaId = 06, AreaId = 00 },
                new SemanaArea { Id = 097, Posicion = 17, SemanaId = 06, AreaId = 00 },
                new SemanaArea { Id = 098, Posicion = 18, SemanaId = 06, AreaId = 00 },
                new SemanaArea { Id = 099, Posicion = 19, SemanaId = 06, AreaId = 00 },
                new SemanaArea { Id = 100, Posicion = 20, SemanaId = 06, AreaId = 00 },


            });
        }
    }
}
