using System;
using System.Collections.Generic;
using System.Text;

namespace Guardias
{
    /// <summary>
    /// Tiene el propósito de servir como fuente de datos
    /// solo por conveniencia, luego se remplará por una bd.
    /// </summary>
    public static class Auxiliar
    {
        public static Area[] areasSemana1 = new Area[]
        {
            new Area { Id = 7, Nombre = "ME Cabo" }, 
            new Area { Id = 5, Nombre = "Hacienda del Mar / Fiestamericana" },
            new Area { Id = 12, Nombre = "Recorrido" },
            new Area { Id = 7, Nombre = "ME Cabo" },
            new Area { Id = 24, Nombre = "Wyndham" },
            new Area { Id = 2, Nombre = "Fiestamericana" }, 
            new Area { Id = 24, Nombre = "Wyndham" }, 
            new Area { Id = 4, Nombre = "Hacienda del Mar" },
            new Area { Id = 6, Nombre = "Marina del Sol" },
            new Area { Id = 17, Nombre = "Sitio / Finisterra" },
            new Area { Id = 1, Nombre = "Casa Dorada" },
            new Area { Id = 18, Nombre = "Sitio / Pueblo Bonito Sunset Beach" },
            new Area { Id = 12, Nombre = "Recorrido" },
            new Area { Id = 21, Nombre = "The Office" },
            new Area { Id = 21, Nombre = "The Office" },
            new Area { Id = 9, Nombre = "Pueblo Bonito" },
            new Area { Id = 19, Nombre = "Sitio / Walmart" },
            new Area { Id = 15, Nombre = "Sitio" },
            new Area { Id = 16, Nombre = "Sitio" },
            new Area { Id = 9, Nombre = "Pueblo Bonito" }
        };

        public static Unidad[] unidades = new Unidad[]
        {
            new Unidad { Id = 01, Numero = 97 },
            new Unidad { Id = 02, Numero = 96 },
            new Unidad { Id = 03, Numero = 95 },
            new Unidad { Id = 04, Numero = 94 },
            new Unidad { Id = 05, Numero = 93 },
            new Unidad { Id = 06, Numero = 92 },
            new Unidad { Id = 07, Numero = 91 },
            new Unidad { Id = 08, Numero = 90 },
            new Unidad { Id = 09, Numero = 89 },
            new Unidad { Id = 10, Numero = 88 },
            new Unidad { Id = 11, Numero = 87 },
            new Unidad { Id = 12, Numero = 86 },
            new Unidad { Id = 13, Numero = 85 },
            new Unidad { Id = 14, Numero = 84 },
            new Unidad { Id = 15, Numero = 83 },
            new Unidad { Id = 16, Numero = 82 },
            new Unidad { Id = 17, Numero = 81 },
            new Unidad { Id = 18, Numero = 80 },
            new Unidad { Id = 19, Numero = 79 },
            new Unidad { Id = 20, Numero = 78 },
            new Unidad { Id = 21, Numero = 77 },
            new Unidad { Id = 23, Numero = 76 },
            new Unidad { Id = 22, Numero = 75 },
            new Unidad { Id = 24, Numero = 74 },
            new Unidad { Id = 25, Numero = 73 },
            new Unidad { Id = 26, Numero = 72 },
            new Unidad { Id = 27, Numero = 71 },
            new Unidad { Id = 28, Numero = 70 },
            new Unidad { Id = 29, Numero = 69 },
            new Unidad { Id = 30, Numero = 68 },
            new Unidad { Id = 31, Numero = 67 },
            new Unidad { Id = 32, Numero = 66 },
            new Unidad { Id = 33, Numero = 65 },
            new Unidad { Id = 34, Numero = 64 },
            new Unidad { Id = 35, Numero = 63 },
            new Unidad { Id = 36, Numero = 62 },
            new Unidad { Id = 37, Numero = 61 },
            new Unidad { Id = 38, Numero = 60 },
            new Unidad { Id = 39, Numero = 59 },
            new Unidad { Id = 40, Numero = 58 },
            new Unidad { Id = 41, Numero = 57 },
            new Unidad { Id = 42, Numero = 56 },
            new Unidad { Id = 43, Numero = 55 },
            new Unidad { Id = 44, Numero = 54 },
            new Unidad { Id = 45, Numero = 53 },
            new Unidad { Id = 46, Numero = 52 },
            new Unidad { Id = 47, Numero = 51 },
            new Unidad { Id = 48, Numero = 50 },
            new Unidad { Id = 49, Numero = 49 },
            new Unidad { Id = 50, Numero = 48 },
            new Unidad { Id = 51, Numero = 47 },
            new Unidad { Id = 52, Numero = 46 },
            new Unidad { Id = 53, Numero = 45 },
            new Unidad { Id = 54, Numero = 44 },
            new Unidad { Id = 55, Numero = 43 },
            new Unidad { Id = 56, Numero = 42 },
            new Unidad { Id = 57, Numero = 41 },
            new Unidad { Id = 58, Numero = 40 },
            new Unidad { Id = 59, Numero = 39 },
            new Unidad { Id = 60, Numero = 38 },
            new Unidad { Id = 61, Numero = 37 },
            new Unidad { Id = 62, Numero = 36 },
            new Unidad { Id = 63, Numero = 35 },
            new Unidad { Id = 64, Numero = 34 },
            new Unidad { Id = 65, Numero = 33 },
            new Unidad { Id = 66, Numero = 32 },
            new Unidad { Id = 67, Numero = 31 },
            new Unidad { Id = 68, Numero = 30 },
            new Unidad { Id = 69, Numero = 29 },
            new Unidad { Id = 70, Numero = 28 },
            new Unidad { Id = 71, Numero = 27 },
            new Unidad { Id = 72, Numero = 26 },
            new Unidad { Id = 73, Numero = 25 },
            new Unidad { Id = 74, Numero = 24 },
            new Unidad { Id = 75, Numero = 23 },
            new Unidad { Id = 76, Numero = 22 },
            new Unidad { Id = 77, Numero = 21 },
            new Unidad { Id = 78, Numero = 20 },
            new Unidad { Id = 79, Numero = 19 },
            new Unidad { Id = 80, Numero = 18 },
            new Unidad { Id = 81, Numero = 17 },
            new Unidad { Id = 82, Numero = 16 },
            new Unidad { Id = 83, Numero = 15 },
            new Unidad { Id = 84, Numero = 14 },
            new Unidad { Id = 85, Numero = 13 },
            new Unidad { Id = 86, Numero = 12 },
            new Unidad { Id = 87, Numero = 11 },
            new Unidad { Id = 88, Numero = 10 },
            new Unidad { Id = 89, Numero = 09 },
            new Unidad { Id = 90, Numero = 08 },
            new Unidad { Id = 91, Numero = 07 },
            new Unidad { Id = 92, Numero = 06 },
            new Unidad { Id = 93, Numero = 05 },
            new Unidad { Id = 94, Numero = 04 },
            new Unidad { Id = 95, Numero = 03 },
            new Unidad { Id = 96, Numero = 02 },
            new Unidad { Id = 97, Numero = 01 },
        };
    }
}
